micronaut:
  application:
    name: register
  server:
    port: ${SERVER_PORT:8080}

endpoints:
  health:
    details-visible: ANONYMOUS

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    keymanager:
      address: ${KEYMANAGER_GRPC_HOST:localhost}:${KEYMANAGER_GRPC_PORT:50051}
      plaintext: true
      max-retry-attempts: 10